export { default as Main } from "./Main";
export { default as Navbar } from "./Navbar";
export { default as Banner } from "./Banner";
export { default as Card } from "./Card";
export { default as Chart } from "./Chart";
export {default as Order} from "./Order";
export {default as TableHead} from "./TableHead";
export {default as TableBody} from "./TableBody";
export {default as Table} from "./Table";
export {default as FilterDiscounts} from "./FilterDiscounts";
